const variable = {
  dateTracker: document.querySelector(".dateTracker"),
  popUp: document.getElementById("popUp"),
  mainArticleOfAllTasks: document.querySelector(".mainArticleOfAllTasks"),
  sectionToDo: document.querySelector(".sectionToDo"),
  taskStatusSection: document.querySelector(".taskStatusSection"),
  finishedTasks: document.querySelector(".finishedTasks"),
  toDoAddTask: document.querySelector(".toDoAddTask"),
  goBackButton: document.getElementById("goBackButton"),
  titleInput: document.getElementById("titleInput"),
  descriptionArea: document.getElementById("descriptionArea"),
  doneButton: document.getElementById("doneButton"),
  shortTaskList: document.querySelector(".shortTaskList"),
  taskFullInfo: document.querySelector(".TaskFullInfo"),
  myTaskShortArticle: document.querySelector(".MyTaskShortArticle"),
  shortFinishedTask: document.querySelector(".shortFinishedTask"),
  buttonDoneTask: document.getElementById("buttonDoneTask"),
  buttonDoneTask: document.getElementById("buttonDoneTask"),
  buttonEditTask: document.getElementById("buttonEditTask"),
  changeTaskValue: document.getElementById("changeTaskValue"),
  taskDescriptionParagraph: document.getElementById("taskDescriptionParagraph"),
  deleteDoneTask: document.getElementById("deleteDoneTask"),
};

export default variable;
